# Generated by Django 5.1.4 on 2024-12-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imoveis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Comercial', 'Comercial'), ('Terreno', 'Terreno')], max_length=50)),
                ('titulo', models.CharField(max_length=250)),
                ('descrição', models.TextField(blank=True, null=True)),
                ('cidade', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('rua', models.CharField(blank=True, max_length=200, null=True)),
                ('quartos', models.IntegerField()),
                ('banheiros', models.IntegerField()),
                ('vagas_garagem', models.IntegerField()),
                ('area', models.FloatField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
