# Generated by Django 5.1.4 on 2024-12-11 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='imoveis',
            options={'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imovel_bairro', to='houses.bairros'),
        ),
    ]
