# Generated by Django 5.1.4 on 2024-12-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_bairros_alter_imoveis_options_alter_imoveis_bairro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairros',
            options={'verbose_name': 'Bairro', 'verbose_name_plural': 'Bairros'},
        ),
        migrations.RenameField(
            model_name='bairros',
            old_name='nome',
            new_name='bairro',
        ),
    ]
