# Generated by Django 5.1.4 on 2024-12-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_bairros_options_rename_nome_bairros_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='imoveis',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='imoveis/'),
        ),
    ]
