# Generated by Django 5.1.4 on 2024-12-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_imoveis_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imoveis',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='imoveis',
            name='titulo',
        ),
        migrations.CreateModel(
            name='ImoveisImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='imagens')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imovel_imagens', to='houses.imoveis')),
            ],
        ),
    ]
