# Generated by Django 5.1.4 on 2024-12-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_remove_imoveis_photo_remove_imoveis_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imoveis',
            name='código',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imoveis',
            name='pretensão',
            field=models.CharField(blank=True, choices=[('Aluguel', 'Aluguel'), ('Venda', 'Venda')], max_length=50, null=True),
        ),
    ]
