# Generated by Django 5.1.4 on 2024-12-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_imoveis_código_imoveis_pretensão'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imoveis',
            options={'verbose_name': 'Imovel', 'verbose_name_plural': 'Imoveis'},
        ),
        migrations.RenameField(
            model_name='imoveis',
            old_name='código',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='imoveis',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='imoveis',
            old_name='pretensão',
            new_name='pretensao',
        ),
    ]
