# Generated by Django 5.1.4 on 2025-03-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_alter_imoveis_options_rename_código_imoveis_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveisimagem',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imovel_imagens', to='houses.imoveis'),
        ),
    ]
